{
    'name': 'EIMS v2',
    'summary': 'EIMS Connector version 2',
    'version': '18.0.1.0.0',
    'category': 'Accounting/Localizations',
    'depends': ['base', 'account', 'web', 'mail','contacts'],
    'data': [
        'security/ir.model.access.csv',
        'data/email_templates.xml',
        'data/eims_sequence.xml',
        'report/eims_invoice_report_templates.xml',
        'report/eims_receipt_report_templates.xml',
        'report/eims_withhold_receipt_report_templates.xml',
        'views/withholding_receipt_views.xml',
        'report/report_action.xml',
        'views/account_move.xml',
        'views/company_eims_view.xml',
        'views/partner_eims_view.xml',
        'views/eims_registered_invoice_views.xml',
        'views/eims_cancel_log_view.xml',
        'views/eims_receipt_log_view.xml',
        'views/eims_credit_log_view.xml',
        'views/eims_notification_log_views.xml',
        'views/eims_unregistered_invoice.xml',
        'views/eims_bulk_cancel.xml',
        'views/eims_bulk_cancel_wizard_view.xml',
        'views/account_move_line_view.xml',

    ],
    'controllers': [
        'controllers/bulk_callback.py',
        'controllers/eims_notification_callback.py',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
